### ISSUE TITLE
Set Up User Authentication

### ISSUE THREAD

**Issue by stephensl** [stephensl/gladtrac#1]
### Tasks:

- [x] Add Devise gem to the Gemfile and run bundle install.

- [x] Generate Devise User model with email and password.

- [x]  Set up Devise views for registration and login.

*Labels:* backend, authentication
