### ISSUE TITLE
Create Database Models

### ISSUE THREAD

**Issue by stephensl** [stephensl/gladtrac#2]
### Tasks:

- [ ] Create and migrate Syllabus model with relevant attributes.

- [ ] Create and migrate Assignment model with associations to Syllabus.

- [ ] Create and migrate Task model with associations to Assignment.

*Labels:* backend, database
